# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' r_ienv
#' Shows current iRODS environment settings
#'
ienv_ <- function() {
    .Call('_rirods_ienv_', PACKAGE = 'rirods')
}

#' ils
#' Lists collections and data objects in iRODS
#' @param args "ils" one or several iRODS data-object (file) or collection (directory) paths
#' @return A data frame with information about collections and data objects under the supplied paths
ils_ <- function(args) {
    .Call('_rirods_ils_', PACKAGE = 'rirods', args)
}

